# Generated by Django 2.1.2 on 2018-11-02 18:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('geocoded_address', models.TextField(blank=True)),
                ('geocoded_latitude', models.FloatField(default=0.0)),
                ('geocoded_longitude', models.FloatField(default=0.0)),
                ('geocoded_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('catchment_area', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('zipcode', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'ordering': ['zipcode'],
            },
        ),
        migrations.AddField(
            model_name='tenantresource',
            name='zipcodes',
            field=models.ManyToManyField(to='nyc.Zipcode'),
        ),
    ]
