# Generated by Django 2.1.2 on 2018-10-21 18:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_fips', models.CharField(max_length=2)),
                ('bldgpostal', models.IntegerField()),
                ('objectid', models.IntegerField()),
                ('id_url', models.CharField(max_length=52)),
                ('cty_fips', models.CharField(max_length=3)),
                ('cartodb_id', models.IntegerField()),
                ('borough', models.CharField(max_length=13)),
                ('state', models.CharField(max_length=2)),
                ('po_name', models.CharField(max_length=19)),
                ('postalcode', models.CharField(max_length=5)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
