# Generated by Django 2.1.2 on 2018-11-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantresource',
            name='boroughs',
            field=models.ManyToManyField(blank=True, to='nyc.Borough'),
        ),
        migrations.AlterField(
            model_name='tenantresource',
            name='neighborhoods',
            field=models.ManyToManyField(blank=True, to='nyc.Neighborhood'),
        ),
        migrations.AlterField(
            model_name='tenantresource',
            name='zipcodes',
            field=models.ManyToManyField(blank=True, to='nyc.Zipcode'),
        ),
    ]
