# Generated by Django 2.1.2 on 2018-10-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zipcode',
            options={'ordering': ['postalcode']},
        ),
    ]
