# Generated by Django 2.1.2 on 2018-10-21 22:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyc', '0002_auto_20181021_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('geocoded_address', models.TextField(blank=True)),
                ('geocoded_latitude', models.FloatField(default=0.0)),
                ('geocoded_longitude', models.FloatField(default=0.0)),
                ('catchment_area', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('zipcodes', models.ManyToManyField(to='nyc.Zipcode')),
            ],
        ),
    ]
