# Generated by Django 2.1.2 on 2018-11-05 11:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyc', '0002_auto_20181102_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityDistrict',
            fields=[
                ('boro_cd', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'ordering': ['boro_cd'],
            },
        ),
        migrations.AddField(
            model_name='tenantresource',
            name='community_districts',
            field=models.ManyToManyField(blank=True, to='nyc.CommunityDistrict'),
        ),
    ]
