# Generated by Django 2.1.2 on 2018-10-21 23:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyc', '0003_tenantresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantresource',
            name='geocoded_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
